version: '3'
services:
    rabbitmq:
        image: rabbitmq:management
        restart: on-failure
        expose:
            - "5672"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - cloud-native-network
    zipkin:
        image: openzipkin/zipkin
        restart: on-failure
        ports:
            - "9411:9411"
        expose:
            - "9411"
        networks:
            - cloud-native-network
    eureka-naming-server:
        build:
            context: ./netflix-eureka-naming-server
            dockerfile: Dockerfile
        networks:
            - cloud-native-network
        expose:
            - 8761
        ports:
            - 8761:8761
    netflix-zuul-api-gateway-server:
        build:
            context: ./netflix-zuul-api-gateway-server
            dockerfile: Dockerfile
        expose:
            - 8755
        ports:
            - 8755:8755
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - cloud-native-network
        depends_on:
            - eureka-naming-server
            - zipkin
            - rabbitmq
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - cloud-native-volume:/var/lib/mysql
        networks:
            - cloud-native-network
volumes:
    cloud-native-volume:
networks:
    cloud-native-network: { }