version: '3'
services:
    netflix-zuul-api-gateway-server:
        build:
            context: netflix-zuul-api-gateway-server
            dockerfile: Dockerfile
        expose:
            - 8755
        ports:
            - 8755:8755
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
#    currency-exchnage-service:
#        build:
#            context: currency-exchange-service
#            dockerfile: Dockerfile
#        expose:
#            - 8000
#        ports:
#            - 8000:8000
#        volumes:
#            - cloud-native-volume:/tmp
#        networks:
#            - envcn_cloud-native-network
#        depends_on:
#            - netflix-zuul-api-gateway-server
    currency-conversion-service:
        build:
            context: currency-conversion-service
            dockerfile: Dockerfile
        expose:
            - 8100
        ports:
            - 8100
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - netflix-zuul-api-gateway-server
    country-service:
        build:
            context: country-service
            dockerfile: Dockerfile
        expose:
            - 8300
        ports:
            - 8300
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - netflix-zuul-api-gateway-server
    rest-api:
        build:
            context: rest-api
            dockerfile: Dockerfile
        expose:
            - 5200
        ports:
            - 5200:5200
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - netflix-zuul-api-gateway-server

volumes:
    cloud-native-volume:
networks:
    envcn_cloud-native-network:
        external: true