version: '3'
services:
    spring-cloud-api-gateway-server:
        container_name: api-gateway
        build:
            context: spring-cloud-api-gateway-server
            dockerfile: Dockerfile
        expose:
            - 8755
        ports:
            - 8755:8755
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
    currency-exchnage-service:
        container_name: c-exchnage-service
        build:
            context: currency-exchange-service
            dockerfile: Dockerfile
        expose:
            - 8000
        ports:
            - 8000:8000
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    currency-conversion-service:
        container_name: c-conversion-service
        build:
            context: currency-conversion-service
            dockerfile: Dockerfile
        expose:
            - 8100
        ports:
            - 8100:8100
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    country-service:
        container_name: country-service
        build:
            context: country-service
            dockerfile: Dockerfile
        expose:
            - 8300
        ports:
            - 8300:8300
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
    api-composer:
        container_name: api-composer
        build:
            context: api-composer
            dockerfile: Dockerfile
        expose:
            - 5200
        ports:
            - 5200:5200
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - spring-cloud-api-gateway-server
volumes:
    cloud-native-volume:
networks:
    envcn_cloud-native-network:
        external: true