version: '3'
services:
    netflix-zuul-api-gateway-server:
        build:
            context: ./netflix-zuul-api-gateway-server
            dockerfile: Dockerfile
        expose:
            - 8755
        ports:
            - 8755:8755
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
    limits-service:
        build:
            context: ./limits-service
            dockerfile: Dockerfile
        expose:
            - 8666
        ports:
            - 8666:8666
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
    currency-exchnage-service:
        build:
            context: ./currency-exchange-service
            dockerfile: Dockerfile
        expose:
            - 8000
        ports:
            - 8000:8000
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - netflix-zuul-api-gateway-server
    currency-conversion-service:
        build:
            context: currency-conversion-service
            dockerfile: Dockerfile
        expose:
            - 8100
        ports:
            - 8100
        volumes:
            - cloud-native-volume:/tmp
        networks:
            - envcn_cloud-native-network
        depends_on:
            - netflix-zuul-api-gateway-server
volumes:
    cloud-native-volume:
networks:
    envcn_cloud-native-network:
        external: true