version: '3'
services:
    rabbitmq:
        image: rabbitmq:management
        restart: on-failure
        expose:
            - "5672"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - cloud-native-network
    zipkin:
        image: openzipkin/zipkin
        restart: on-failure
        ports:
            - "9411:9411"
        expose:
            - "9411"
        networks:
            - cloud-native-network
    config-server:
        build:
            context: ../spring-cloud-config-server
            dockerfile: Dockerfile
        expose:
            - 8888
        ports:
            - 8888:8888
        networks:
            - cloud-native-network
    eureka-naming-server:
        build:
            context: ../netflix-eureka-naming-server
            dockerfile: Dockerfile
        networks:
            - cloud-native-network
        expose:
            - 8761
        ports:
            - 8761:8761
    db:
        image: mysql
        restart: on-failure
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - cloud-native-volume:/var/lib/mysql
        networks:
            - cloud-native-network
volumes:
    cloud-native-volume:
networks:
    cloud-native-network:
