version: '3'
services:
    postgresdb:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'password'
        ports:
            - '3312:5432'
        expose:
            - '5432'
        volumes:
            - postgresdbTemp:/var/lib/postgresql/data
        networks:
            - envcn_cloud-native-network
volumes:
    postgresdbTemp:
networks:
    envcn_cloud-native-network:
        external: true